---
# **Table of Contents**
---

**1.** [**Array Initialization**](#Section1)<br>
**2.** [**Array Initialization using Random Numbers**](#Section2)<br>
**3.** [**Numpy Indexing**](#Section3)<br>
  - **3.1** [**Array Slicing**](#Section31)
  - **3.2** [**Conditional Array Indexing**](#Section32)

**4.** [**Numpy Array Operations**](#Section4)<br>
  - **4.1** [**Numpy Broadcasting**](#Section41)
  - **4.2** [**Numpy Mathematical Functions**](#Section42)
  - **4.3** [**Numpy Unique Items and Counts**](#Section43)
  - **4.4** [**Array Manipulation**](#Section44)
    - **4.4.1** [**Array Shape Manipulation**](#Section441)
    - **4.4.2** [**Array Merging & Splitting**](#Section442)

**5.** [**Conclusion**](#Section5)<br>

In [1]:
import numpy as np

---
<a name = Section1></a>
# **1. Array Initialization**
---

- In this section, we will learn some array initalization methods such as:

  - **.arange():** Generates an array of specifed range, step size (default is 1) and type of data to be stored.

  - **.zeros():** Generate an array containing zero values.

  - **.ones():** Generates an array containing ones as value.

  - **.linspace():** Generates an evenly spaced numbers over a specified interval.

  - **.eye():** Generates a 2-D array with ones on the diagonal and zeros elsewhere.
  
  - **.empty():** Generates an array with random values.

In [2]:
# Generating an array of size 10 with a step size of 1
np.arange(0,10,1,dtype=None)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Generating an array of size 10 with a step size of 2
np.arange(0,10,2,dtype=None)

array([0, 2, 4, 6, 8])

Specifying your data type

While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.

In [4]:
x = np.arange(0,5,1, dtype=np.int64)
x

array([0, 1, 2, 3, 4])

In [5]:
x.dtype

dtype('int64')

In [6]:
# Generates an array of size 5 containing zeros
x=np.zeros(shape=5) 
x

array([0., 0., 0., 0., 0.])

In [7]:
x.dtype  # default data type is float64

dtype('float64')

In [8]:
# Generates an array of size 3 X 3 containing zeros
x=np.zeros(shape=(3,3))

# Display the resolution of two_dim_zeros variable
print("Dimentions:",x.ndim)

# Output the result
x

Dimentions: 2


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# Generates an array of size 3 X 3 containing ones
np.ones(shape=(3, 3)) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# Create an empty array with 2 elements
# The function empty creates an array whose initial content is random and depends on the state of the memory. 
# The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

np.empty(2)

array([4.65448579e-310, 0.00000000e+000])

In [11]:
# Generates an evenly spaced numbers from 0 to 5
np.linspace(0,10,num=5,dtype=np.int64)

array([ 0,  2,  5,  7, 10])

In [12]:
# Generates a 2-D array with ones on the diagonal and zeros elsewhere
np.eye(N=3,M=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<a name = Section2></a>
# **2. Random Array Initialization**
---

- In this section we are going to see how to populate array with random numbers.

- We will get to know about the following two function of numpy:

  - **.random.rand():** Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

  - **.random.randn():** Return a sample (or samples) from the “standard normal” distribution of mean 0 and variance 1.

In [13]:
# Generates an array of 5 random values
np.random.rand(5)

array([0.19822288, 0.1658819 , 0.91025145, 0.23601578, 0.8962851 ])

In [14]:
# Generates an array of random values having resolution of 5 X 5
np.random.rand(5,5)

array([[0.62744681, 0.67363914, 0.8972794 , 0.46940818, 0.4402532 ],
       [0.70493715, 0.78765542, 0.21422775, 0.83932887, 0.06689476],
       [0.13282013, 0.99527784, 0.35359242, 0.17748962, 0.30506537],
       [0.74438003, 0.26754608, 0.46950228, 0.35346951, 0.77599339],
       [0.69396463, 0.10333725, 0.61874764, 0.42086023, 0.95178085]])

In [15]:
# Generates an array of random values having resolution of 4 X 4
np.random.randn(4,4)

array([[-0.76114221,  0.00163844,  1.1774952 , -1.46809069],
       [-1.26090044, -1.1181793 , -0.52383818,  0.18832283],
       [-0.12900558, -0.91138372, -0.41159238,  0.13912695],
       [-1.19889532,  0.07252674,  0.07392714,  1.32639539]])

In [16]:
# Generates an array of 6 random values
rand_array = np.random.rand(6)

# Display array containing random values
print('Random Array', rand_array)

# Display the resolution of the rand_array variable
print('Array Resolution:', rand_array.ndim)

# Reshape the 1-D array to 3 X 2 array and output the result
rand_array.reshape(3, 2) 

Random Array [0.34932562 0.30448289 0.55413289 0.13537695 0.51201892 0.57596077]
Array Resolution: 1


array([[0.34932562, 0.30448289],
       [0.55413289, 0.13537695],
       [0.51201892, 0.57596077]])

In [17]:
# With np.reshape, you can specify a few optional parameters:
np.reshape(rand_array, newshape=(1, 6), order='C')

array([[0.34932562, 0.30448289, 0.55413289, 0.13537695, 0.51201892,
        0.57596077]])

a - is the array to be reshaped.

newshape - is the new shape you want. You can specify an integer or a tuple of integers. If you specify an integer, the result will be an array of that length. The shape should be compatible with the original shape.

order - C means to read/write the elements using C-like index order, F means to read/write the elements using Fortran-like index order, A means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. (This is an optional parameter and doesn’t need to be specified.)

**Observation:**

- In various applications(like assigning weights in **Artificial Neural Networks**) arrays need to be initialized randomly.

<a name = Section3></a>
# **3. Numpy Indexing**
---

- In this section we will show how numpy based elements are indexed and how to access these elements.

In [18]:
# Creating an array of 10 values ranging from 0 to 11
my_array=np.arange(11)

# Display the array elements
print('Full Array:', my_array)

# Display the element present at index 1
print('First element:', my_array[1])

Full Array: [ 0  1  2  3  4  5  6  7  8  9 10]
First element: 1


**Observation:**

- We just saw that we can access individual elements of an array by calling them by their indices.

<a name = Section31></a>
## **3.1 Array Slicing**

- To access more than one element of an array use slicing operations.

In [19]:
# Creating an array of 10 values ranging from 0 to 11
my_arr = np.arange(0, 11, 1)

# Display the array elements
print('Full Array:', my_arr)

Full Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [20]:
# Accessing elements ranging from index 1 to 5
my_arr[1:5]

array([1, 2, 3, 4])

- **Note:** The first element that is extracted is of index 1 and the last element to be extracted is of index 5-1=4.

In [21]:
# Accessing elements ranging from index 8 onwards
my_arr[8:]

array([ 8,  9, 10])

In [22]:
# Accessing elements ranging till index 6
my_arr[:6]

array([0, 1, 2, 3, 4, 5])

- **Note:** Numpy arrays are **mutable**. It implies that you can change the values of the array.

In [23]:
# Mapping value -5 ranging index 0 to 5
my_arr[0:5]=-5

In [24]:
my_arr

array([-5, -5, -5, -5, -5,  5,  6,  7,  8,  9, 10])

- You can also perform slicing operations on 2-D array.

In [25]:
# Initializing an array of resolution 4 X 3
arr2d = np.array([[1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12]])

In [26]:
# Ouput the 2-D array
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
# It could also be achieved using arange(0, 12), and then using reshape(4, 3)
arr2d = np.arange(12).reshape(4,3)

In [28]:
arr2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
# Accessing element present at 0th row and 2nd column
arr2d[0,2]

2

In [30]:
# Accessing elements from rows (1st and 2nd) and columns (1st and 2nd)
arr2d[0:2,0:2]

array([[0, 1],
       [3, 4]])

In [31]:
# Accessing elements from rows (till 2nd) and columns (1st onwards)
arr2d[:2,1:]

array([[1, 2],
       [4, 5]])

**Observation:**

- So, through these examples we have seen that we can access one or multiple elements of an array using slicing.

- Also at times when needed we can extract subarrays from an array.

<a name = Section32></a>
## **3.2 Conditional Array Indexing**

- Here, we will observe how to **filter** element of an **array** based on some conditions.

- First, we need to create a **boolean array** based on an conditional statement using **conditional operators** for comparison.

- Then this boolean array is passed as index of the original array to return the filtered elements.

In [32]:
# Create a list of elements
my_list=[1,2,3,4,5,6]

# Cast to numpy array
arr = np.array(object=my_list)

# Display the array elements
print("Elements:",arr)

# Output boolean values (True for element greater than 2)
arr>2

Elements: [1 2 3 4 5 6]


array([False, False,  True,  True,  True,  True])

In [33]:
# Initialize an array ranging from 2 to 15
my_array = np.arange(2,15)

# Display the elements of an array
print('Array:', my_array)

# Display the lenght of array
print('Length:',len(my_array))


Array: [ 2  3  4  5  6  7  8  9 10 11 12 13 14]
Length: 13


In [34]:
# Example 1: Output elements that have True as condition
my_array[[True, False, True, False, True, False, False, False, False, False, False, False, False]]

array([2, 4, 6])

In [35]:
# Example 2: Output elements that have True as condition
my_array[[False, False, False, False, False, False, False, True, True, True, True, True, True]]

array([ 9, 10, 11, 12, 13, 14])

In [36]:
# Output boolean values (True for element greater than 8)
my_array>8

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True])

In [37]:
# Output actual values based on the condition passed (elements greater than 8)
my_array[my_array>8]

array([ 9, 10, 11, 12, 13, 14])

In [38]:
# Output values present at index 1 and 4
my_array[[1,4]]

array([3, 6])

In [39]:
# Output elements that have True as condition
my_array[[False, True, False, False, True, False, False, False, False, False, False, False, False]]

array([3, 6])

**Observation:**

- Use conditional indexing to filter out some values like null or outliers in an array.

- Given below is a table where you can see what are the various operators available in Python.

<center><img src="https://www.oreilly.com/library/view/visual-basic-2012/9781118332085/images/f253-01.jpg"></center>

---
<a name = Section4></a>
# **4. Numpy Array Operations**
---

- In this section we will observe various arithmatic operations on numpy arrays.

<a name = Section41></a>
## **4.1 Numpy Broadcasting**

- The term broadcasting describes **how numpy treats arrays** with **different shapes** during arithmetic operations. 

- Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

- Broadcasting provides a means of **vectorizing array operations** so that looping occurs in C instead of Python. 

- It does this **without** making **needless copies of data** and usually leads to efficient algorithm implementations. 

- There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

- NumPy operations are usually done on pairs of arrays on an element-by-element basis. 

- In the simplest case, the two arrays must have exactly the same shape, as in the following example:

In [40]:
# First array of three elements
a = np.array([1.0, 2.0, 3.0])

# Second array of three elements
b = np.array([2.0, 2.0, 2.0])

# Output the result of broadcasting
a*b

array([2., 4., 6.])

In [41]:
# Output the result of broadcasting
a+b

array([3., 4., 5.])

- NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 

- The simplest broadcasting example occurs when an array and a scalar value are combined in an operation:

In [42]:
# An array of three elements
a = np.array([1.0, 2.0, 3.0])


# Initialize variable with scalar value
b = 2.0

# Output the result of broadcasting
a * b

array([2., 4., 6.])

In [43]:
# Initialized array of resolution 4 X 3
my_arr = np.arange(1,13).reshape(4,3)

# Initialize scaler with a constant value
scalar = 3

# Display the shape of 2-D array
print('Shape of Array:', my_arr.shape)

# Output the 2-D array
my_arr

Shape of Array: (4, 3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
# Output of broadcasting scalar value to the array
my_arr + scalar

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

**Observation:**

- We can observe that scalar is stretched and is added to all of the elements of an array.

In [45]:
# Initialized 1-D array
arr_1d = np.array([10, 10, 10])

# Display the shape of 1-D array
print('shape:', arr_1d.shape)

# Output the 1-D array
arr_1d

shape: (3,)


array([10, 10, 10])

In [46]:
# Ouput broadcasted values to the 2-D array
my_arr + arr_1d

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

**Observation:**

- We observed that array with lower dimension i.e. arr_1d is stretched such that it matches the dimensions of arr_2d.

- Let's learn it better with one diagramatic example.

<center><img src="https://github.com/insaid2018/Term-1/blob/master/Images/broadcasting.png?raw=true"></center>

- From the above image you can see how and when the **data** is **stretched** to carry out the mathematical operations. 

- Here we have performed addition on arrays of varying dimensions. Always Remember to stretch the data as per the __broadcasting rules.__

- Now lets look at a different shape of array.

In [47]:
# Initialized 2-D array
arr = np.array([[1, 1, 1, 1]])

# Display the shape of 2-D array
print('shape:', arr.shape)

# Output the 2-D array
arr

shape: (1, 4)


array([[1, 1, 1, 1]])

In [48]:
# Ouput broadcasted values to the 2-D array
arr_2d + arr

NameError: ignored

**Observation:**

- If the **dimensions do not match** it will **throw** an **exception**.

- It is **advisable** to **keep a note of the shape** or dimension of the arrays before applying any mathematical operation.

- And make sure they satisfy the broadcasting rules else value error may occur.

<a name = Section42></a>
## **4.2 Numpy Mathematical Functions**

- In this section we will observe faster and optimized mathematicalfunctions that we can apply for large size arrays.

- We will try out following functions with respect to an array:

  - **.min():** Return the minimum along a given axis.

  - **.max():** Return the maximum along a given axis.

  - **.argmin():** Returns the indices of the minimum values along an axis.

  - **.argmax():** Returns the indices of the maximum values along an axis.

  - **.sqrt():** Return the non-negative square-root of an array, element-wise.

  - **.mean():** Compute the arithmetic mean along the specified axis.

  - **.exp():** Calculate the exponential of all elements in the input array.

In [ ]:
# Initialize an array of elements ranging from 1 to 11
arr= np.arange(1,11)

# Output the array
arr

In [ ]:
print('Minimum value in an array:', arr.min())
print('Maximum value in an array:', arr.max())
print('Minimum index in an array:', arr.argmin())
print('Maximum index in an array:', arr.argmax())
print('Mean of an array:', arr.mean())

In [ ]:
arr = np.array([ 5,  2,  3,  4,  1,  6,  7,  8,  9, 10])

In [ ]:
print('Minimum value in an array:', arr.min())
print('Maximum value in an array:', arr.max())
print('Minimum index in an array:', arr.argmin())
print('Maximum index in an array:', arr.argmax())
print('Mean of an array:', arr.mean())

In [ ]:
print('Square Root of elements in an array:', np.sqrt(arr))
print('Exponent of elements in an array:', np.exp(arr))

- You can aggregate matrices the same way you aggregated vectors:

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

In [ ]:
data.max()

In [ ]:
data.min()

In [ ]:
data.sum()

- You can aggregate all the values in a matrix and you can aggregate them across columns or rows using the axis parameter:

In [ ]:
data.max(axis=0)

In [ ]:
data.max(axis=1)

**Observation:**

- We saw various methods to do various mathematical operations like minimum, maximum, finding mean, finding exponent.

- There are more functions available to calculate various statistical parameters.

<a name = Section43></a>
## **4.3 How to get unique items and counts**

- **You can find the unique elements in an array easily with np.unique.**

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
    
unique_values = np.unique(a)
print(unique_values)

- **To get the indices of unique values in a NumPy array (an array of first index positions of unique values in the array), just pass the return_index argument in np.unique() as well as your array.**

In [ ]:
unique_values,unique_index = np.unique(a,return_index=True)

print(unique_values)
print(unique_index)

- **You can pass the return_counts argument in np.unique() along with your array to get the frequency count of unique values in a NumPy array.**

In [ ]:
unique_values,occurrence_count = np.unique(a, return_counts=True)

print(occurrence_count, end="\n")
print(unique_values)

- **This also works with 2D arrays! If you start with this array:**

In [ ]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [ ]:
unique_values = np.unique(a_2d)
print(unique_values)

- **If the axis argument isn’t passed, your 2D array will be flattened.**

- **If you want to get the unique rows or columns, make sure to pass the axis argument. To find the unique rows, specify axis=0 and for columns, specify axis=1.**

In [ ]:
a_2d

In [ ]:
unique_rows = np.unique(a_2d, axis=0)

unique_rows

In [ ]:
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)

In [ ]:
print(unique_rows)

In [ ]:
print(indices)

In [ ]:
print(occurrence_count)

<a name = Section44></a>
## **4.4 Array Manipulation**

- In this section we will see some numpy functions that can change the structure (shape) of an array.

<a name = Section441></a>
### **4.4.1 Array Shape Manipulation**

- We will explore following functions that will perform array shape manipulation:

  - **.reshape():** Gives a new shape to an array without changing its data.

  - **.flatten():** Return a copy of the array collapsed into one dimension.

  - **.transpose()**: Reverse or permute the axes of an array and returns the modified array.
  
  - **.flip()** : Function allows you to flip, or reverse, the contents of an array along an axis.

In [ ]:
# Initialize an array of elements ranging from 0 to 116
arr = np.arange(0,16)

# Output the array
arr

In [ ]:
# Reshaping array with resolution of 4 X 4 
arr_2D = arr.reshape(4, 4)

arr_2D

In [ ]:
# Transform 2-D array to 1-D array
arr_2D.flatten()

In [ ]:
# Transpose the elements of 2-D array
arr_2D.transpose()

In [ ]:
# Reversing a 1D array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)

In [ ]:
# Reversing a 2D array

arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)

print("Normal Array:")
print(arr_2d)

print("Reversed Array")
print(reversed_arr)

In [ ]:
# Reverse only the rows with:

reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

In [ ]:
# Reverse only the columns with:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

In [ ]:
# Reverse the contents of only one column or row. 
# For example, you can reverse the contents of the row at index position 1 (the second row):

In [ ]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

In [ ]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

<a name = Section442></a>
### **4.4.2 Array Merging and Splitting**

- We will explore following functions that will perform array merging and splitting:

  - **.concatenate():** Join a sequence of arrays along an existing axis.

  - **.hsplit():** Split an array into multiple sub-arrays horizontally (column-wise).

  - **.vsplit():** Split an array into multiple sub-arrays vertically (row-wise).
  
  - **.sort():** Sorting an array.

In [ ]:
# Initialize a first 2-D array of shape 2 X 4
arr_x = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8]])

# Initialize a second 2-D array of shape 2 X 4
arr_y = np.array([[21, 22, 23, 24], 
                  [25, 26, 27, 28]])

In [ ]:
# Concatenation of two 2-D arrays column-wise
concat_col_wise = np.concatenate((arr_x, arr_y), axis=1)

# Output the result of concatenation of two 2-D arrays column-wise
concat_col_wise

In [ ]:
# Concatenation of two 2-D arrays row-wise
concat_row_wise = np.concatenate((arr_x, arr_y), axis=0)

# Output the result of concatenation of two 2-D arrays row-wise
concat_row_wise

In [ ]:
# Split an array into multiple sub-arrays horizontally (column-wise)
horizontal = np.hsplit(ary=concat_row_wise, indices_or_sections=2)

# Output the result
horizontal

In [ ]:
# Split an array into multiple sub-arrays horizontally (column-wise)
verticle = np.vsplit(ary=concat_row_wise, indices_or_sections=2)

# Output the result
verticle

- **Sorting an element**

In [ ]:

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

In addition to sort, which returns a sorted copy of an array, you can use:

 - argsort, which is an indirect sort along a specified axis,

- lexsort, which is an indirect stable sort on multiple keys,

- searchsorted, which will find elements in a sorted array, and

- partition, which is a partial sort.

**Observation:**

- Using **concatenate** function we can merge arrays **columnwise** and **rowwise**. 

- Also arrays can be **horizontally** and **vertically** spliited using hsplit and vsplit.

---
<a name = Section5></a>
# **5. Conclusion**
---

- **Numpy** is an **open-source** add-on module to Python.

- By using Numpy you can **speed up** your **workflow** operations.

- You can **interface** with **other packages** in the Python ecosystem that use Numpy under the hood.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays.

- It provides common mathematical and numerical routines in pre-compiled, fast functions.

- It **provides basic routines** for manipulating large arrays and matrices of numeric data.

- NumPy arrays have a fixed size decided at the time of creation. 

- Changing the size of an array will create a new array and delete the original.

- The **elements** in a NumPy array are all **required** to be of the **same data type**, and thus will be the same size in memory.

- NumPy arrays **facilitate advanced mathematical** and other types of **operations** on large numbers of data.