**Data Cleaning and Preparation**

In [113]:
import numpy as np

In [114]:
import pandas as pd

In [115]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [116]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [117]:
string_data[0] = None

In [118]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

**Filtering Out Missing Data**

In [119]:
from numpy import nan as NA

In [120]:
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [121]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [122]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])

In [123]:
cleaned = data.dropna()

In [124]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [125]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [126]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [127]:
data[4] = NA

In [128]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [129]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [130]:
df = pd.DataFrame(np.random.randn(7, 3))

In [131]:
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA

In [132]:
df

0         1         2
0 -0.922327       NaN       NaN
1  0.482605       NaN       NaN
2 -0.319212       NaN -0.541897
3 -2.409531       NaN -0.892843
4 -0.108640 -0.758672 -0.743462
5 -0.217101 -0.866710 -0.737277
6  0.161560  0.457434 -0.104505

In [133]:
df.dropna()

0         1         2
4 -0.108640 -0.758672 -0.743462
5 -0.217101 -0.866710 -0.737277
6  0.161560  0.457434 -0.104505

In [134]:
df.dropna(thresh=2)

0         1         2
2 -0.319212       NaN -0.541897
3 -2.409531       NaN -0.892843
4 -0.108640 -0.758672 -0.743462
5 -0.217101 -0.866710 -0.737277
6  0.161560  0.457434 -0.104505

**Filling In Missing Data**

In [135]:
df.fillna(0)

0         1         2
0 -0.922327  0.000000  0.000000
1  0.482605  0.000000  0.000000
2 -0.319212  0.000000 -0.541897
3 -2.409531  0.000000 -0.892843
4 -0.108640 -0.758672 -0.743462
5 -0.217101 -0.866710 -0.737277
6  0.161560  0.457434 -0.104505

In [136]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -0.922327  0.500000  0.000000
1  0.482605  0.500000  0.000000
2 -0.319212  0.500000 -0.541897
3 -2.409531  0.500000 -0.892843
4 -0.108640 -0.758672 -0.743462
5 -0.217101 -0.866710 -0.737277
6  0.161560  0.457434 -0.104505

In [137]:
_ = df.fillna(0, inplace=True)
df

0         1         2
0 -0.922327  0.000000  0.000000
1  0.482605  0.000000  0.000000
2 -0.319212  0.000000 -0.541897
3 -2.409531  0.000000 -0.892843
4 -0.108640 -0.758672 -0.743462
5 -0.217101 -0.866710 -0.737277
6  0.161560  0.457434 -0.104505

In [138]:
df = pd.DataFrame(np.random.randn(6, 3))

In [139]:
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA

In [140]:
df

0         1         2
0  0.058338  0.284630 -1.032962
1  0.190108  0.069764  1.142889
2 -0.834125       NaN -1.802285
3 -0.022883       NaN -0.433804
4 -0.042821       NaN       NaN
5 -1.918810       NaN       NaN

In [141]:
df.fillna(method='ffill')

0         1         2
0  0.058338  0.284630 -1.032962
1  0.190108  0.069764  1.142889
2 -0.834125  0.069764 -1.802285
3 -0.022883  0.069764 -0.433804
4 -0.042821  0.069764 -0.433804
5 -1.918810  0.069764 -0.433804

In [142]:
df.fillna(method='ffill', limit=2)

0         1         2
0  0.058338  0.284630 -1.032962
1  0.190108  0.069764  1.142889
2 -0.834125  0.069764 -1.802285
3 -0.022883  0.069764 -0.433804
4 -0.042821       NaN -0.433804
5 -1.918810       NaN -0.433804

In [143]:
data = pd.Series([1., NA, 3.5, NA, 7])

In [144]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [145]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

**Data Transformation**

**  Removing Duplicates**

In [146]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})

In [147]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [148]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [149]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [150]:
data['v1'] = range(7)

In [151]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [152]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

**Transforming Data Using a Function or Mapping**

In [153]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [154]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [155]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}

In [156]:
lowercased = data['food'].str.lower()

In [157]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [158]:
data['animal'] = lowercased.map(meat_to_animal)

In [159]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [160]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

**Replacing Values**

In [161]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [162]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [163]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [164]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [165]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [166]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [167]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [168]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [169]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [170]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

**Renaming Axis Indexes**

In [171]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [172]:
transform = lambda x: x[:4].upper()

In [173]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [174]:
data.index = data.index.map(transform)

In [175]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [176]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [177]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [178]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [179]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

**Discretization and Binning**

In [180]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [181]:
bins = [18, 25, 35, 60, 100]

In [182]:
cats = pd.cut(ages, bins)

In [183]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [184]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [185]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [186]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [187]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [188]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [189]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [190]:
data = np.random.rand(20)

In [191]:
pd.cut(data, 4, precision=2)

[(0.5, 0.74], (0.00077, 0.25], (0.74, 0.99], (0.74, 0.99], (0.74, 0.99], ..., (0.00077, 0.25], (0.00077, 0.25], (0.00077, 0.25], (0.25, 0.5], (0.25, 0.5]]
Length: 20
Categories (4, interval[float64]): [(0.00077, 0.25] < (0.25, 0.5] < (0.5, 0.74] < (0.74, 0.99]]

In [192]:
data = np.random.randn(1000)

In [193]:
cats = pd.qcut(data, 4)

In [194]:
cats

[(-3.483, -0.726], (-3.483, -0.726], (-3.483, -0.726], (-3.483, -0.726], (-0.00302, 0.698], ..., (-3.483, -0.726], (-0.726, -0.00302], (-0.00302, 0.698], (-0.00302, 0.698], (-0.00302, 0.698]]
Length: 1000
Categories (4, interval[float64]): [(-3.483, -0.726] < (-0.726, -0.00302] < (-0.00302, 0.698] <
                                    (0.698, 3.008]]

In [195]:
pd.value_counts(cats)

(0.698, 3.008]        250
(-0.00302, 0.698]     250
(-0.726, -0.00302]    250
(-3.483, -0.726]      250
dtype: int64

In [196]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-3.483, -1.264], (-3.483, -1.264], (-1.264, -0.00302], (-1.264, -0.00302], (-0.00302, 1.258], ..., (-1.264, -0.00302], (-1.264, -0.00302], (-0.00302, 1.258], (-0.00302, 1.258], (-0.00302, 1.258]]
Length: 1000
Categories (4, interval[float64]): [(-3.483, -1.264] < (-1.264, -0.00302] < (-0.00302, 1.258] <
                                    (1.258, 3.008]]

**Detecting and Filtering Outliers**

In [197]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [198]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.028839     0.032865    -0.035301    -0.004665
std       1.034016     1.016284     1.011013     0.980126
min      -3.074139    -3.131830    -2.963921    -3.191705
25%      -0.686471    -0.625986    -0.690213    -0.686819
50%       0.034015     0.066840    -0.042013     0.007028
75%       0.731216     0.714440     0.651105     0.630620
max       3.700850     2.589482     3.131925     2.871546

In [199]:
col = data[2]

In [200]:
col[np.abs(col) > 3]

915    3.131925
Name: 2, dtype: float64

In [201]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
53   3.194982 -0.787452 -1.809611  0.442126
245 -0.082328  0.174632  0.576115 -3.191705
509  0.833735 -3.084763  1.527018  0.286685
652  3.700850 -0.000518 -0.207611 -0.560168
720 -3.074139 -1.220550 -0.752720 -0.704157
850  3.080965 -3.131830 -0.759564  0.936459
915 -0.039050 -0.824796  3.131925 -1.232910

In [202]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [203]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.027937     0.033081    -0.035433    -0.004473
std       1.030721     1.015624     1.010608     0.979520
min      -3.000000    -3.000000    -2.963921    -3.000000
25%      -0.686471    -0.625986    -0.690213    -0.686819
50%       0.034015     0.066840    -0.042013     0.007028
75%       0.731216     0.714440     0.651105     0.630620
max       3.000000     2.589482     3.000000     2.871546

In [204]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0 -1.0  1.0
1  1.0  1.0 -1.0  1.0
2  1.0  1.0 -1.0  1.0
3  1.0  1.0 -1.0 -1.0
4  1.0  1.0  1.0 -1.0

**Permutation and Random Sampling**

In [205]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [206]:
sampler = np.random.permutation(5)

In [207]:
sampler

array([3, 1, 4, 0, 2])

In [208]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [209]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
1   4   5   6   7
4  16  17  18  19
0   0   1   2   3
2   8   9  10  11

In [210]:
df.sample(n=3)

0   1   2   3
2   8   9  10  11
0   0   1   2   3
3  12  13  14  15

In [211]:
choices = pd.Series([5, 7, -1, 6, 4])

In [212]:
choices

0    5
1    7
2   -1
3    6
4    4
dtype: int64

In [213]:
draws = choices.sample(n=10, replace=True)

In [214]:
draws

1    7
2   -1
0    5
3    6
0    5
3    6
1    7
4    4
0    5
1    7
dtype: int64

**Computing Indicator/Dummy Variables**

In [215]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})

In [216]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [217]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [218]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [219]:
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [220]:
df_with_dummy = df[['data1']].join(dummies)

In [221]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [222]:
mnames = ['movie_id', 'title', 'genres']

In [223]:
mnames

['movie_id', 'title', 'genres']

In [224]:
movies = pd.read_table('/content/sample_data/movies.dat', sep='::',
                       header=None, names=mnames)

/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py:767: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return read_csv(**locals())


In [225]:
movies

movie_id  ...                        genres
0            1  ...   Animation|Children's|Comedy
1            2  ...  Adventure|Children's|Fantasy
2            3  ...                Comedy|Romance
3            4  ...                  Comedy|Drama
4            5  ...                        Comedy
...        ...  ...                           ...
3878      3948  ...                        Comedy
3879      3949  ...                         Drama
3880      3950  ...                         Drama
3881      3951  ...                         Drama
3882      3952  ...                Drama|Thriller

[3883 rows x 3 columns]

In [226]:
all_genres = []

In [227]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [228]:
genres = pd.unique(all_genres)

In [229]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [230]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [231]:
zero_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [232]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [233]:
dummies

Animation  Children's  Comedy  ...  Mystery  Film-Noir  Western
0           0.0         0.0     0.0  ...      0.0        0.0      0.0
1           0.0         0.0     0.0  ...      0.0        0.0      0.0
2           0.0         0.0     0.0  ...      0.0        0.0      0.0
3           0.0         0.0     0.0  ...      0.0        0.0      0.0
4           0.0         0.0     0.0  ...      0.0        0.0      0.0
...         ...         ...     ...  ...      ...        ...      ...
3878        0.0         0.0     0.0  ...      0.0        0.0      0.0
3879        0.0         0.0     0.0  ...      0.0        0.0      0.0
3880        0.0         0.0     0.0  ...      0.0        0.0      0.0
3881        0.0         0.0     0.0  ...      0.0        0.0      0.0
3882        0.0         0.0     0.0  ...      0.0        0.0      0.0

[3883 rows x 18 columns]

In [234]:
gen = movies.genres[0]

In [235]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [236]:
gen

"Animation|Children's|Comedy"

In [237]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [238]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [239]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [240]:
movies_windic

movie_id  ... Genre_Western
0            1  ...           0.0
1            2  ...           0.0
2            3  ...           0.0
3            4  ...           0.0
4            5  ...           0.0
...        ...  ...           ...
3878      3948  ...           0.0
3879      3949  ...           0.0
3880      3950  ...           0.0
3881      3951  ...           0.0
3882      3952  ...           0.0

[3883 rows x 21 columns]

In [241]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [242]:
np.random.seed(12345)

In [243]:
values = np.random.rand(10)

In [244]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [245]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [246]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

**String Manipulation**

**String Object Methods**

In [247]:
val = 'a,b,  guido'

In [248]:
val.split(',')

['a', 'b', '  guido']

In [249]:
pieces = [x.strip() for x in val.split(',')]

In [250]:
pieces

['a', 'b', 'guido']

In [251]:
first, second, third = pieces

In [252]:
first + '::' + second + '::' + third

'a::b::guido'

In [253]:
'::'.join(pieces)

'a::b::guido'

In [254]:
'guido' in val

True

In [255]:
val.index(',')

1

In [256]:
val.find(':')

-1

In [257]:
val.count(',')

2

In [258]:
val.replace(',', '::')

'a::b::  guido'

In [259]:
val

'a,b,  guido'

In [260]:
val.replace(',', '')

'ab  guido'

**Regular Expressions**

In [261]:
import re

In [262]:
text = "foo    bar\t baz  \tqux"

In [263]:
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [264]:
regex = re.compile('\s+')

In [265]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [266]:
regex.findall(text)

['    ', '\t ', '  \t']

In [267]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

In [268]:
text

'Dave dave@google.com\nSteve steve@gmail.com\nRob rob@gmail.com\nRyan ryan@yahoo.com\n'

In [269]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [270]:
regex = re.compile(pattern, flags=re.IGNORECASE)
# re.IGNORECASE makes the regex case-insensitive

In [271]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [272]:
m = regex.search(text)

In [273]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [274]:
text[m.start():m.end()]

'dave@google.com'

In [275]:
print(regex.match(text))

None


In [276]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [277]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [278]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [279]:
m = regex.match('wesm@bright.net')

In [280]:
m

<re.Match object; span=(0, 15), match='wesm@bright.net'>

In [281]:
m.groups()

('wesm', 'bright', 'net')

In [282]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [283]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



**Vectorized String Functions in pandas**

In [284]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
        'Rob': 'rob@gmail.com', 'Wes': np.nan}

In [285]:
data = pd.Series(data)

In [286]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [287]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [288]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [289]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [290]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [291]:
matches = data.str.match(pattern, flags=re.IGNORECASE)

In [292]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [293]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [294]:
PREVIOUS_MAX_ROWS = pd.options.display.max_rows

In [295]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS

In [296]:
PREVIOUS_MAX_ROWS

60